## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux
  - osx
  
julia:
  - 0.7
  - 1.0
  - nightly
  
matrix:
  allow_failures:
    - os: osx
    - julia: nightly
  
notifications:
  email: true

git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.instantiate(); Pkg.test("BHAtp"; coverage=true)'
  
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("BHAtp")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BHAtp")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
